# Generated by Django 4.0.1 on 2022-01-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pay_date',
            field=models.DateField(),
        ),
    ]
