# Generated by Django 4.0.1 on 2022-03-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='address_one',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='address_two',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='postal_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
