# Generated by Django 4.0.1 on 2022-02-15 16:09

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
